### ISSUE TITLE
Add Setting to clear data for the page site that's being moved

### ISSUE THREAD

**Issue by Caspy7** [stoically/firefox-add-on-switch-container-plus#2]
One of the main points, privacy-wise, for containers is to prevent sites from following you or knowing about your actions.

When moving Facebook to its own container I went into history, right clicked an entry for it and clicked "forget". This clears all offline storage for it such as logins, cookies, site preferences and history.
If a user thoughtlessly logs into a site or browses a site that may start to to build a trail of their usage (e.g. through cookies), that site can potentially begin to track them during normal browsing again.

Clearing data gives the option to easily clear the trail.

**Comment by stoically** [comment]
Hey, thanks for the issue. Unfortunately clearing container storage and history isn't in the scope of this Add-on, it should merely allow you to switch to a different container.

Something more advanced might be using [Temporary Containers](https://addons.mozilla.org/firefox/addon/temporary-containers/) for each new tab and Permanent Containers by using the [Multi-Account Containers Add-on](https://addons.mozilla.org/firefox/addon/multi-account-containers/).

However, "Moving" a Website from your default ("no") container to a Permanent Container is a nice idea - and essentially what [Facebook Container](https://addons.mozilla.org/firefox/addon/facebook-container/) is doing. Might be interesting to look into building an Add-on for exactly that purpose. I've actually thought about [something similar](https://github.com/stoically/temporary-containers/issues/49#issue-295724433) as on-boarding for Temporary Containers.

**Comment by Caspy7** [comment]
I actually discussed this with the Facebook container dev(s).
It does not move the data. Per the description on the page:
> Installing this extension deletes your Facebook cookies and logs you out of Facebook.

I suggested that it move the data. At least one dev's response was:
> i'd agree that it would feel more seamless; on the other hand you could also say, from an UX perspective, it feels like "ah, ok, now i have to login because i'm in container" as opposed to "why i'm still logged in? does this even work?"

I think not having the annoyance of having to log back in is preferable.

I just think moving the data would dovetail perfectly with your addon.

**Comment by stoically** [comment]
> At least one dev's response was

Yeah, that was me :D

> I just think moving the data would dovetail perfectly with your addon.

Switching the current tab to a different Container is a completely different thing than "Delete Cookies in the current Container, copy the Cookies over into a new Container and make sure that in the future all requests to that Domain are redirected into that Container."
